"""empty message

Revision ID: 06d0ca95955d
Revises: e690df8a205c
Create Date: 2018-05-04 00:02:43.833148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06d0ca95955d'
down_revision = 'e690df8a205c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('alarm_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'alarm_time')
    # ### end Alembic commands ###
